function k(b,a,d,c){b.v.gb(b.lb,a,d,c)}function l(b,a,d,c){b.v.ca?k(b,a,d,c):b.v.De()._OnMessageFromDOM({type:"event",component:b.lb,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.v.C(b.lb,a,d)}function aa(b,a){for(const [d,c]of a)q(b,d,c)}function t(b){b.Rb||(b.v.nd(b.Vd),b.Rb=!0)}window.Fb=class{constructor(b,a){this.v=b;this.lb=a;this.Rb=!1;this.Vd=()=>this.Ka()}dd(){}Ka(){}};
window.mf=class{constructor(){this.$c=-1}j(){-1!==this.$c&&(self.clearTimeout(this.$c),this.$c=-1)}};"use strict";class ba{constructor(b){this.Hc=b;this.Kc=!1;this.Rc=!0}}function ca(b,a){const d=a.elementId,c=b.hd(d,a),e=new ba(c);b.ob.set(d,e);c.style.boxSizing="border-box";c.style.display="none";e.Rc=!!a.isVisible;a=b.xc(c);a.addEventListener("focus",()=>{da(b,"elem-focused",d)});a.addEventListener("blur",()=>{da(b,"elem-blurred",d)});b.Nb&&document.body.appendChild(c)}
function ea(b,a){q(b,"get-element",d=>{const c=u(b,d.elementId);return a(c,d)})}function u(b,a){b=b.ob.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Hc}function da(b,a,d){var c;c||(c={});c.elementId=d;k(b,a,c)}
window.oe=class extends self.Fb{constructor(b){super(b,"button");this.ob=new Map;this.Nb=!0;aa(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const d=u(this,a);this.Nb&&d.parentElement.removeChild(d);this.ob.delete(a)}],["set-visible",a=>{if(this.Nb){var d=this.ob.get(a.elementId),c=d.Hc;d.Kc?c.style.display=a.isVisible?"":"none":d.Rc=!!a.isVisible}}],["update-position",a=>{if(this.Nb){var d=this.ob.get(a.elementId),c=d.Hc;c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=
a.width+"px";c.style.height=a.height+"px";a=a.fontSize;null!==a&&(c.style.fontSize=a+"em");d.Kc||(d.Kc=!0,d.Rc&&(c.style.display=""))}}],["update-state",a=>{const d=u(this,a.elementId);this.uc(d,a)}],["focus",a=>{const d=this.xc(u(this,a.elementId));a.focus?d.focus():d.blur()}],["set-css-style",a=>{const d=u(this,a.elementId),c=a.prop;a=a.val;c.startsWith("--")?d.style.setProperty(c,a):d.style[c]=a}],["set-attribute",a=>{u(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{u(this,
a.elementId).removeAttribute(a.name)}]]);ea(this,a=>a)}hd(){throw Error("required override");}uc(){throw Error("required override");}xc(b){return b}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ia=0;
function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.bf?new Promise(d=>{const c="c3_resolve_"+ia;++ia;self[c]=d;a.textContent=b.ff+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}let ja=!1,ka=!1;function na(){if(!ja){try{new Worker("blob://",{get type(){ka=!0}})}catch(b){}ja=!0}return ka}let y=new Audio;
const oa={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const D=[],F=new Map,G=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.hb=class b{constructor(a){this.ca=a.hf;this.wa=null;this.ba="";this.Xa=a.ef;this.Cb={};this.Qa=this.ua=null;this.Pb=[];this.J=this.na=null;this.Oc=!1;this.Cd=0;this.rb=null;this.Wa=-1;this.Ye=()=>this.Le();this.Va=[];this.ad=null;this.Wd=[];this.A=a.Xd;this.Sb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&na()||(this.ca=!1);this.ca&&ha&&(this.ca=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ca=!1;if("cordova"===
this.A&&this.ca)if(v){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);d&&90<=parseInt(d[1],10)||(this.ca=!1)}else this.ca=!1;this.eb()?self.chrome.webview.addEventListener("message",d=>this.sd(d.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=d=>this.sd(d));this.Vb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",d=>this.He(d));this.C("runtime","create-job-worker",()=>this.Ie());this.C("runtime","send-wrapper-extension-message",d=>this.Oe(d));"cordova"===this.A?document.addEventListener("deviceready",()=>this.qd(a)):this.qd(a)}j(){this.vc();this.wa&&(this.wa=this.wa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}se(){return fa&&"cordova"===this.A}qc(){const a=
navigator.userAgent;return fa&&ta.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}qe(){return v}kd(){return v&&ta.has(this.A)}eb(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async qd(a){"macos-wkwebview"===this.A?this.ib({type:"ready"}):this.eb()&&(this.Re(),this.Wd=(await this.Ge()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.Vb={};await this.ze();
for(let c=0,e=a.Za.length;c<e;++c){var d=a.Za[c];this.Vb.hasOwnProperty(d)?a.Za[c]={bf:!0,ff:this.Vb[d]}:this.ra.hasOwnProperty(d)&&(a.Za[c]=URL.createObjectURL(this.ra[d]))}a.jc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let c=0;this.nd(()=>{c++;document.body.style.opacity=0===c%2?"1":"0.999"})}a.df?this.ba=a.df:(d=location.origin,this.ba=("null"===d?"file:///":d)+location.pathname,d=this.ba.lastIndexOf("/"),-1!==d&&(this.ba=this.ba.substr(0,d+1)));a.kf&&(this.Cb=a.kf);
d=new MessageChannel;this.wa=d.port1;this.wa.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.Ke(c));this.rb=new self.te(this);await va(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.ca?await this.Fe(a,d.port2):
await this.Ee(a,d.port2)}yc(a){a=this.Cb.hasOwnProperty(a)?this.Cb[a]:a.endsWith("/workermain.js")&&this.Cb.hasOwnProperty("workermain.js")?this.Cb["workermain.js"]:"playable-ad"===this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.A&&this.Sb)return a=await this.Eb(c.af?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=
new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}pd(a){var d=this.ba,c=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.cb(),m=a.qf,n=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,B=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.Xd;var r=(new URLSearchParams(self.location.search)).has("debug"),C=this.rb;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:B,swClientId:x,exportType:a,isDebug:r,ife:!!self.pf,jobScheduler:{inputPort:C.Nc,outputPort:C.Vc,maxNumWorkers:C.Ve},supportedAudioFormats:oa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Sb,isiOSCordova:this.se(),isiOSWebView:this.qc(),isWebView2Wrapper:this.eb(),wrapperComponentIds:this.Wd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Fe(a,d){const c=this.yc(a.jf);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const n=p=>{this.ua.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():m()};this.ua.addEventListener("message",n);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(c,this.ba)).toString()})})):this.ua=await this.lc(c,this.ba,{type:"module",name:"Runtime",af:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.jc||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.A)for(let h=0,m=a.ic.length;h<
m;++h){const n=a.ic[h],p=n[0];if(p===a.bd||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.La(p)}this.ua.postMessage(Object.assign(this.pd(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ic,mainProjectScript:a.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...wa(this.rb)]);this.Pb=D.map(h=>new h(this));this.od();xa(this.na);self.c3_callFunction=(h,m)=>{var n=this.na;return n.v.md(n.lb,
"js-invoke-function",{name:h,params:m})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.gb("runtime","go-to-last-error-script"))}async Ee(a,d){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=D.map(g=>new g(this));this.od();var c=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.jc)){var e=[...a.jc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);c.unshift(...e)}c=await Promise.all(c.map(g=>this.La(g)));await Promise.all(c.map(g=>w(g)));c=self.C3_ProjectScriptsStatus;e=a.bd;const f=a.ic;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await w(h),"preview"!==this.A||c[g]||this.td(g,"main script did not run to completion")}catch(m){this.td(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await w(h);"preview"===this.A&&"object"!==typeof self.lf.nf?
(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.pd(a),{isInWorker:!1,messagePort:d,canvas:this.J,runOnStartupFunctions:sa}),xa(this.na),this.rd(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}td(a,d){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,
d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}rd(){this.Kb()}Kb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ie(){const a=await ya(this.rb);return{outputPort:a,transferables:[a]}}De(){if(this.ca)throw Error("not available in worker mode");return this.Qa}gb(a,d,c,e,f){this.wa.postMessage({type:"event",component:a,handler:d,
dispatchOpts:e||null,data:c,responseId:null},f)}md(a,d,c,e,f){const g=ra++,h=new Promise((m,n)=>{G.set(g,{resolve:m,reject:n})});this.wa.postMessage({type:"event",component:a,handler:d,dispatchOpts:e||null,data:c,responseId:g},f);return h}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.Je(a);if("result"===d)this.Me(a);else if("runtime-ready"===d)this.Ne();else if("alert-error"===d)this.Kb(),alert(a.message);else if("creating-runtime"===d)this.rd();else throw Error(`unknown message '${d}'`);
}Je(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=F.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}Jb(a,
d,c){let e;c&&c.transferables&&(e=c.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}Me(a){const d=a.responseId,c=a.isOk;a=a.result;const e=G.get(d);c?e.resolve(a):e.reject(a);G.delete(d)}C(a,d,c){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);e.set(d,c)}static Db(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}od(){for(const a of this.Pb)if("runtime"===a.lb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}Ke(a){this.gb("debugger","message",a)}Ne(){for(const a of this.Pb)a.dd()}static cb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static ud(a){ua=!!a}nd(a){this.Va.push(a);this.Dc()}Qe(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.vc()}Dc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Ye))}vc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}Le(){this.Wa=
-1;for(const a of this.Va)a();this.Dc()}Ba(a){this.na.Ba(a)}Ja(a){this.na.Ja(a)}Cc(){this.na.Cc()}Ib(a){this.na.Ib(a)}re(){return!!oa["audio/webm; codecs=opus"]}async Se(a){a=await this.md("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ve(a){this.Oc=!0;this.Cd=a}pe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ld(a){return!this.pe(a)}async La(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Sb&&this.ld(a))?(a.startsWith(this.ba)&&
(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async He(a){const d=a.filename;switch(a.as){case "text":return await this.ne(d);case "buffer":return await this.Eb(d);default:throw Error("unsupported type");}}gd(a){const d=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async ne(a){a=await this.gd(a);return await pa(a)}wc(){if(z.length&&!(8<=A)){A++;
var a=z.shift();this.Ae(a.filename,a.gf,a.$e)}}Eb(a){return new Promise((d,c)=>{z.push({filename:a,gf:e=>{A--;this.wc();d(e)},$e:e=>{A--;this.wc();c(e)}});this.wc()})}async Ae(a,d,c){try{const e=await this.gd(a),f=await qa(e);d(f)}catch(e){c(e)}}sd(a){if("entered-fullscreen"===a)b.ud(!0),H(this.na);else if("exited-fullscreen"===a)b.ud(!1),H(this.na);else if("object"===typeof a){const d=a.type;"wrapper-init-response"===d?(this.ad(a),this.ad=null):"extension-message"===d?this.gb("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Oe(a){this.ib({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}ib(a){this.eb()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Re(){window.moveTo=(a,d)=>{this.ib({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(d)})};window.resizeTo=
(a,d)=>{this.ib({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(d)})}}Ge(){return this.eb()?new Promise(a=>{this.ad=a;this.ib({type:"wrapper-init"})}):Promise.resolve()}async ze(){const a=[];for(const [d,c]of Object.entries(this.ra))a.push(this.ye(d,c));await Promise.all(a)}async ye(a,d){if("object"===typeof d)this.ra[a]=new Blob([d.str],{type:d.type}),this.Vb[a]=d.str;else{let c=await this.Ce(d);c||(c=this.Be(d));this.ra[a]=c}}async Ce(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}Be(a){a=this.Pe(a);return this.xe(a.data,a.cf)}Pe(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{cf:a,data:c}}xe(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(c&=
3;c--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:d})}};"use strict";const I=self.hb;function za(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};
function Da(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function Ea(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}
function Fa(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function Ga(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await K(b);var c=await Fa(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await K(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await Ga(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let La=!1;document.addEventListener("pause",()=>La=!0);document.addEventListener("resume",()=>La=!1);function xa(b){b.Bd=!0;b.Sc=b.v.pa();b.sb=b.v.ia()}function H(b){if(!b.$){var a=I.cb();a&&"any"!==b.Yc&&Ma(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Na(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Oa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Pa(b){return await self.C3_GetSvgImageSize(b.blob)}function Qa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ra(b){self.setTimeout(()=>{b.Ad=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Sa(b,!0)),document.addEventListener("resume",()=>Sa(b,!1))):document.addEventListener("visibilitychange",()=>Sa(b,"hidden"===document.visibilityState));b.Zb=!("hidden"!==document.visibilityState&&!La);return{isSuspended:b.Zb}}
function Ta(b){b.wd||(b.wd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ua(b){b.vd||(b.vd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Va(b){await Da(b.url)}
function Wa(b,a){b.Dd=a.message;-1===b.Ic&&(b.Ic=setTimeout(()=>{b.Ic=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Dd)},250))}function Xa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.cb(),innerWidth:b.pa(),innerHeight:b.ia()})}function Sa(b,a){b.Zb!==a&&((b.Zb=a)?b.v.vc():b.v.Dc(),k(b,"visibilitychange",{hidden:a}))}
function Ya(b,a,d){"Backspace"===d.key&&L(d);if(!b.$){var c=Aa.get(d.code)||d.code;l(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},J)}}function Za(b,a,d,c){b.$||za(d)||l(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.da,pageX:d.pageX,pageY:d.pageY+b.da,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}
function ab(b){window!==window.top&&window.focus();bb(b.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,d){if(!b.$){var c=0;"mouse"===d.pointerType&&(c=b.xb);l(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.da,pageX:d.pageX,pageY:d.pageY+b.da,movementX:d.movementX||0,movementY:d.movementY||0,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},J);"mouse"===d.pointerType&&(c=
"mousemove","pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),Za(b,c,d,Ba),b.xb=d.buttons)}}
function cb(b,a,d){if(!b.$&&!za(d)){var c=b.xb;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.da,pageX:d.pageX,pageY:d.pageY+b.da,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},J);b.xb=d.buttons;Za(b,d.type,d,Ba)}}
function N(b,a,d){if(!b.$)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
J)}}function db(b,a,d){document.body.style.transform="";b.da=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function eb(b,a,d,c){const e=b.pa(),f=b.ia();b.Ya=-1;e!=a||f!=d?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.cb()}):10>c&&fb(b,e,f,c+1)}
function fb(b,a,d,c){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>eb(b,a,d,c),48)}
function Ma(b){b=b.Yc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Db(class extends self.Fb{constructor(b){super(b,"runtime");this.Id=!0;this.Bd=!1;this.Ya=-1;this.Yc="any";this.Zb=this.vd=this.wd=!1;this.ec=document.createElement("div");this.ec.className="c3-screen-reader-text";this.ec.setAttribute("aria-live","polite");document.body.appendChild(this.ec);this.Ea=null;this.$=!1;this.Dd="";this.Ic=-1;this.Ad=!1;this.Sc=b.pa();this.sb=b.ia();this.da=this.Bb=0;b.C("canvas","update-size",c=>{var e=this.v;e.Oc||(e=e.J,e.style.width=c.styleWidth+"px",e.style.height=
c.styleHeight+"px",e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",c.displayScale),this.Id&&(e.style.display="",this.Id=!1))});b.C("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",c=>Na(c));b.C("runtime","raster-svg-image",c=>Oa(c));b.C("runtime",
"get-svg-image-size",c=>Pa(c));b.C("runtime","set-target-orientation",c=>{this.Yc=c.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",c=>Qa(c));b.C("runtime","go-to-script",c=>Qa(c));b.C("runtime","before-start-ticking",()=>Ra(this));b.C("runtime","debug-highlight",c=>{if(c.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display=
"";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ta(this));b.C("runtime","enable-device-motion",()=>Ua(this));b.C("runtime","add-stylesheet",c=>Va(c));b.C("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",c=>{alert(c.message)});
b.C("runtime","screen-reader-text",c=>{var e=c.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+c.id,e.textContent=c.text,this.ec.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+c.id))?e.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===e?(e=document.getElementById("c3-sr-"+c.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",c=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.ve(c.duration)});b.C("runtime","export-to-video-progress",c=>Wa(this,c));b.C("runtime","exported-to-video",c=>{window.Ze({type:"exported-video",
arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.C("runtime","exported-to-image-sequence",c=>{window.Ze({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||Ha(e)||c.preventDefault()});const d=b.J;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);d.addEventListener("selectstart",L);d.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),d.addEventListener("pointerdown",L)):d.addEventListener("touchstart",L);this.xb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ka,{passive:!1});window.addEventListener("wheel",Ka,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Bd){var c=this.pa();var e=this.ia();if(this.v.kd()){if(this.Ad){if(this.Sc===
c&&e<this.sb){this.Bb=this.sb-e;db(this,this.sb,this.Bb);c=void 0;break a}0<this.Bb&&(this.Bb=0,db(this,e,this.Bb))}this.Sc=c;this.sb=e}k(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.cb()});this.v.qc()&&(-1!==this.Ya&&clearTimeout(this.Ya),eb(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",c=>Xa(this,c));window.addEventListener("webkitfullscreenerror",c=>Xa(this,c));window.addEventListener("mozfullscreenerror",c=>Xa(this,c));if(b.qc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):Ha(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});this.Ra=new Set;this.Xb=new WeakSet;this.va=!1}dd(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=!1}k(this,"window-blur",{parentHasFocus:a},Ca);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&
k(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>Ya(this,"keydown",a));window.addEventListener("keyup",a=>Ya(this,"keyup",a));window.addEventListener("dblclick",a=>Za(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{ab(a);M(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{ab(a);cb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>cb(this,
"pointermove",a)),window.addEventListener("mouseup",a=>cb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{ab(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Cc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.qe()&&!this.v.kd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.v.pa()}ia(){return this.v.ia()}Cc(){var b=[...this.Ra];this.Ra.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Xb.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Xb.delete(b);let a;try{a=b.play()}catch(d){this.Ra.add(b);return}a&&a.catch(()=>{this.Xb.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Xb.add(b)}Ib(b){this.va=!!b}});"use strict";async function va(b){if(b.Te)throw Error("already initialised");b.Te=!0;var a=b.xa.yc(("playable-ad"===b.xa.A?b.xa.Xa:"")+"dispatchworker.js");b.Gc=await b.xa.lc(a,b.kb,{name:"DispatchWorker"});a=new MessageChannel;b.Nc=a.port1;b.Gc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Vc=await ya(b)}
function wa(b){return[b.Nc,b.Vc]}async function ya(b){const a=b.Jd.length;var d=b.xa.yc(("playable-ad"===b.xa.A?b.xa.Xa:"")+"jobworker.js");d=await b.xa.lc(d,b.kb,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.Gc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.Jd.push(d);return e.port1}
self.te=class{constructor(b){this.xa=b;this.kb=b.ba;this.kb="preview"===b.A?this.kb+"workers/":this.kb+b.Xa;this.Ve=Math.min(navigator.hardwareConcurrency||2,16);this.Gc=null;this.Jd=[];this.Vc=this.Nc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.hb({hf:!0,jf:"workermain.js",Za:["scripts/c3runtime.js"],ic:[],bd:"",ef:"scripts/",jc:[],Xd:"html5"}));"use strict";
async function gb(b,a){a=a.type;let d=!0;0===a?d=await ib():1===a&&(d=await jb());k(b,"permission-result",{type:a,result:d})}async function ib(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function jb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.hb.Db(class extends self.Fb{constructor(b){super(b,"touch");q(this,"request-permission",a=>gb(this,a))}});"use strict";const kb=180/Math.PI;
async function lb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.Zc=a.timeScaleMode;b.Od=["equalpower","HRTF","soundfield"][a.panningModel];b.zd=["linear","inverse","exponential"][a.distanceModel];b.Pd=a.refDistance;b.Nd=a.maxDistance;b.Rd=a.rolloffFactor;if(b.v.Oc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.Cd)});else{var d={latencyHint:a.latencyHint};b.Ud||(d.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(d);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(d);else throw Error("Web Audio API not supported");mb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&mb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(c=>
O(b,c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct] Preloading sounds failed: ",c)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function nb(b,a){var d=a.originalUrl,c=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,n=a.pos,p=a.panning,B=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Kd=g.slice(0);ob(b,g);try{b.R=await pb(b,d,c,e,g,f);if(p){P(b.R,!0);var r=b.R,C=p.innerAngle,la=p.outerAngle,ma=p.outerGain;if(r.qb){qb(r,p.x,p.y,p.z,p.angle);var E=self.$a.we;r.sa[0]!==E(C)&&
(r.sa[0]=E(C),r.F.coneInnerAngle=E(C));r.sa[1]!==E(la)&&(r.sa[1]=E(la),r.F.coneOuterAngle=E(la));r.sa[2]!==ma&&(r.sa[2]=ma,r.F.coneOuterGain=ma)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof B&&0!==B?(Q(b.R,!0),rb(b.R,B)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,m,n,x)}catch(Db){console.error("[Construct] Audio: error starting playback: ",Db);return}finally{d=g.join(" ");c=b.zb.get(d);if(!c)throw Error("expected pending tag");c.cd--;0===c.cd&&(c.resolve(),b.zb.delete(d))}t(b)}
async function sb(b,a){var d=a.tags;const c=a.vol,e=a.duration;a=a.stopOnEnd;await tb(b,d);for(const h of R(b,d))if(!h.Pa){d=h.G.gain;d.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;d.setValueAtTime(d.value,f);d.linearRampToValueAtTime(c,g);h.Ha=c;h.Oa=g;h.Td=a}S(b)}async function ub(b,a){const d=a.tags;a=a.rate;await tb(b,d);for(const c of R(b,d))c.ma!==a&&(c.ma=a,c.Ca())}async function vb(b,a){const d=a.tags;a=a.pos;await tb(b,d);for(const c of R(b,d))c.rc(a)}
async function wb(b,a){const d=a.originalUrl,c=a.url,e=a.type;a=a.isMusic;try{await pb(b,d,c,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function xb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function yb(b,a){const d=a.type;var c=a.tags;const e=a.params;let f;if("convolution"===d)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of c){if("filter"===d)c=new self.ce(b,...e);else if("delay"===d)c=new self.ae(b,...e);else if("convolution"===d){var g=c=new self.$d(b,f.ja,...e),h=a.bufferType;g.xd=a.bufferOriginalUrl;g.yd=h}else if("flanger"===d)c=new self.de(b,...e);else if("phaser"===
d)c=new self.fe(b,...e);else if("gain"===d)c=new self.ee(b,...e);else if("stereopan"===d)c=new self.he(b,...e);else if("tremolo"===d)c=new self.ie(b,...e);else if("ringmod"===d)c=new self.ge(b,...e);else if("distortion"===d)c=new self.be(b,...e);else if("compressor"===d)c=new self.Zd(b,...e);else if("analyser"===d)c=new self.Yd(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let n=g.la.get(h);n||(n=[],g.la.set(h,n));c.Hd=n.length;c.Xc=h;n.push(c);zb(g,h)}Ab(b)}
async function Bb(b,a){const d=a.saveLoadMode;if(3!==d){var c=[];for(var e of b.H)e.za()&&1===d||!e.za()&&2===d?c.push(e):e.j();b.H=c}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.fc=a.timeScale;b.Jc=a.gameTime;c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);c=a.listenerOrientation;if(Array.isArray(c)){for(e=0;6>e;++e)b.ea[e]=c[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Ib(b.va);b.Wb=a.masterVolume;b.Na.gain.value=
b.Wb;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(g=>yb(b,g))));await Promise.all(c);await Promise.all(a.playing.map(f=>Cb(b,f,d)));S(b)}
async function Eb(b,a){try{const d=b.g.suspend(a.time);b.Gd?b.g.resume():(b.g.startRendering().then(c=>{const e=[];for(let f=0,g=c.numberOfChannels;f<g;++f){const h=c.getChannelData(f);e.push(h.buffer)}b.v.gb("runtime","offline-audio-render-completed",{duration:c.duration,length:c.length,numberOfChannels:c.numberOfChannels,sampleRate:c.sampleRate,channelData:e},null,e)}).catch(c=>Gb(c)),b.Gd=!0);await d}catch(d){Gb(d)}}
function mb(b){b.Qb||(b.Mc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Qb=!0)}
async function O(b,a,d,c,e,f){for(var g of b.ka)if(g.bb()===d)return await Hb(g),g;if(f)return null;if(e&&(b.ac||b.Fd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===c&&!b.Ud;e&&f&&(b.Fd=!0);d=!e||b.ac||f?new self.le(b,a,d,c,e,f):new self.je(b,a,d,c,e);b.ka.push(d);await Hb(d);b.Md.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:d.ha()}),b.Md.add(a));return d}
function Ib(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Jb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function zb(b,a){a=a.toLowerCase();let d=b.ga();var c=b.la.get(a);if(c&&c.length){d=c[0].N();for(let f=0,g=c.length;f<g;++f){var e=c[f];f+1===g?e.U(b.ga()):e.U(c[f+1].N())}}for(const f of Kb(b,a))c=d,e=f.fa||f.F||f.G,e.disconnect(),e.connect(c);b.Fa&&b.Tc===a&&(b.Fa.disconnect(),b.Fa.connect(d))}
function*Kb(b,a){if(a)for(const d of b.H)Ib(0<d.oa.length?d.oa[0]:"",a)&&(yield d);else b.R&&!b.R.O()&&(yield b.R)}function Lb(b,a,d){return d?b.v.Se(a).then(c=>{const e=b.g.createBuffer(1,c.length,48E3);e.getChannelData(0).set(c);return e}):new Promise((c,e)=>{b.g.decodeAudioData(a,c,e)})}function Mb(b,a){let d=0;for(let c=0,e=b.H.length;c<e;++c){const f=b.H[c];b.H[d]=f;f.P===a?f.j():++d}b.H.length=d}
function*R(b,a){if(0<a.length)for(const c of b.H){a:{b=c.oa;var d=a;for(const e of d){d=!1;for(const f of b)if(Ib(f,e)){d=!0;break}if(!d){b=!1;break a}}b=!0}b&&(yield c)}else b.R&&!b.R.O()&&(yield b.R)}async function pb(b,a,d,c,e,f){for(const g of b.H)if(g.bb()===d&&(g.kc()||f))return g.oa=e,g;a=await O(b,a,d,c,f);e="html5"===a.Ec?new self.ke(a.s,a,e):new self.me(a.s,a,e);b.H.push(e);return e}
function ob(b,a){a=a.join(" ");let d=b.zb.get(a);if(!d){let c=null;d={cd:0,promise:new Promise(e=>c=e),resolve:c};b.zb.set(a,d)}d.cd++}function tb(b,a){return(b=b.zb.get((0===a.length?b.Kd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ma.size)t(b);else for(const a of b.H)if(!a.I&&!a.O()){t(b);break}}function Nb(b,a,d,c){k(b,"trigger",{type:a,tags:d,aiid:c})}function Ab(b){b.Pc||(b.Pc=!0,Promise.resolve().then(()=>Ob(b)))}
function Ob(b){const a={};for(const [d,c]of b.la)a[d]=c.map(e=>e.ab());k(b,"fxstate",{fxstate:a});b.Pc=!1}
async function Cb(b,a,d){if(3!==d){var c=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,n=a.volume,p=a.playbackTime;if(!g||1!==d)if(g||2!==d){d=null;try{d=await pb(b,c,e,f,h,g)}catch(B){console.error("[Construct] Audio: error loading audio state: ",B);return}b=d;(c=a.pan)?(P(b,!0),e=b.F,f=c.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=c.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.sa[0]=c.cia,b.sa[1]=c.coa,b.sa[2]=
c.cog,e.coneInnerAngle=c.cia,e.coneOuterAngle=c.coa,e.coneOuterGain=c.cog,b.qa=c.uid):P(b,!1);b=d;c=a.stereoPan;"number"!==typeof c?Q(b,!1):(Q(b,!0),rb(b,c));d.Play(m,n,p,0);a.isPlaying||d.fb();d.Ac(a)}}}function Gb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.Fb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Qb=this.Mc=!1;this.ya=()=>{if(!this.Mc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var d=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=d;c.connect(a.destination);c.start(0);"running"===a.state&&this.Qb&&(this.Mc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Qb=!1)}};this.ka=[];this.H=[];this.R=null;this.Kd=[];this.Md=new Set;this.Ld=-1;this.zb=new Map;this.Wb=1;this.va=!1;this.Zc=0;this.fc=1;this.Jc=0;this.Od="HRTF";this.zd="inverse";this.Pd=600;this.Nd=1E4;this.Rd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Fd=this.ac=!1;this.Ud=this.v.re();this.la=new Map;this.Ma=new Set;this.Gd=this.Pc=!1;this.Tc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,d)=>{this.Fa&&this.Fa.disconnect();this.Tc=d.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Jb(this,this.Tc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Na.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>lb(this,a)],["play",a=>nb(this,a)],["stop",a=>{a=a.tags;for(const d of R(this,a))d.Aa()}],["stop-all",()=>{for(const a of this.H)a.Aa()}],["set-paused",a=>{const d=a.tags;a=a.paused;for(const c of R(this,d))a?c.fb():c.Hb();S(this)}],["set-volume",
a=>{const d=a.tags;a=a.vol;for(const c of R(this,d))T(c,a)}],["fade-volume",a=>sb(this,a)],["set-master-volume",a=>{this.Wb=a.vol;this.Na.gain.value=this.Wb}],["set-muted",a=>{const d=a.tags;a=a.isMuted;for(const c of R(this,d))Pb(c,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Ib(this.va);for(const d of this.H)d.Lb()}],["set-looping",a=>{const d=a.tags;a=a.isLooping;for(const c of R(this,d))c.sc(a)}],["set-playback-rate",a=>ub(this,a)],["set-stereo-pan",a=>{const d=a.tags;a=a.p;for(const c of R(this,
d))Q(c,!0),rb(c,a)}],["seek",a=>vb(this,a)],["preload",a=>wb(this,a)],["unload",a=>xb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const d of this.H)d.tc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>yb(this,a)],["set-effect-param",a=>{var d=a.tags;const c=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of d)d=this.la.get(h.toLowerCase()),!d||0>c||c>=d.length||d[c].Z(e,
f,g,a);Ab(this)}],["remove-effects",a=>{a=a.tags;for(const d of a){a=d.toLowerCase();const c=this.la.get(a);if(!c||!c.length)break;for(const e of c)e.j();this.la.delete(a);zb(this,a)}}],["tick",a=>{this.fc=a.timeScale;this.Jc=a.gameTime;this.Ld=a.tickCount;if(0!==this.Zc)for(var d of this.H)d.Ca();!(d=a.listenerPos)||this.aa[0]===d[0]&&this.aa[1]===d[1]&&this.aa[2]===d[2]||(this.aa[0]=d[0],this.aa[1]=d[1],this.aa[2]=d[2],this.g.listener.setPosition(d[0],d[1],d[2]));if((d=a.listenerOrientation)&&(this.ea[0]!==
d[0]||this.ea[1]!==d[1]||this.ea[2]!==d[2]||this.ea[3]!==d[3]||this.ea[4]!==d[4]||this.ea[5]!==d[5])){for(let c=0;6>c;++c)this.ea[c]=d[c];this.g.listener.setOrientation(...this.ea)}for(const c of a.instPans){a=c.uid;for(const e of this.H)e.qa===a&&qb(e,c.x,c.y,c.z,c.angle)}}],["load-state",a=>Bb(this,a)],["offline-render-audio",a=>Eb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Na}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Gb(){return this.va}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();
b=this.g.currentTime;for(var a of this.H)a.Ka(b);a=this.H.filter(d=>!d.I&&!d.O()).map(d=>d.ab());k(this,"state",{tickCount:this.Ld,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(d=>({tag:d.Xc,index:d.Hd,peak:d.Ua,rms:d.Qd,binCount:d.l.frequencyBinCount,freqBins:d.Ed}))});0===a.length&&0===this.Ma.size&&this.Rb&&(this.v.Qe(this.Vd),this.Rb=!1)}static we(b){return b*kb}static jd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ue(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.hb.Db(self.$a);"use strict";function Hb(b){b.Ub||(b.Ub=b.zc());return b.Ub}self.ed=class{constructor(b,a,d,c,e){this.s=b;this.Xe=a;this.Ga=d;this.T=c;this.Ue=e;this.Ec="";this.Ub=null}j(){this.Ub=this.s=null}zc(){}V(){return this.s.V()}nc(){return this.Xe}bb(){return this.Ga}mc(){return this.T}za(){return this.Ue}ha(){}};"use strict";
self.je=class extends self.ed{constructor(b,a,d,c,e){super(b,a,d,c,e);this.Ec="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.V().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.V().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Mb(this.s,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}zc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ga})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Qb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.A&&a.ld(b.Ga)&&a.Sb)b.Da=await a.Eb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Rb(b){if(b.ja)return b.ja;b.ja=await Lb(b.s,b.Da,b.We);b.Da=null}
self.le=class extends self.ed{constructor(b,a,d,c,e,f){super(b,a,d,c,e);this.Ec="webaudio";this.ja=this.Da=null;this.We=!!f}j(){Mb(this.s,this);this.ja=this.Da=null;super.j()}async zc(){try{await Qb(this),await Rb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Sb=0;
function P(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Od,b.F.distanceModel=b.s.zd,b.F.refDistance=b.s.Pd,b.F.maxDistance=b.s.Nd,b.F.rolloffFactor=b.s.Rd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function Q(b,a){a=!!a;b.Tb!==a&&(b.Tb=a,b.Tb?(P(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function rb(b,a){b.Tb&&b.Wc!==a&&(b.fa.pan.value=a,b.Wc=a)}function T(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.oc()}function Pb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Lb())}
function qb(b,a,d,c,e){if(b.qb){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==d||f[2]!==c)f[0]=a,f[1]=d,f[2]=c,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Qc?b.s.Jc:performance.now()/1E3}
self.fd=class{constructor(b,a,d){this.s=b;this.P=a;this.oa=d;this.Mb=Sb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.qb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Tb=!1;this.Wc=0;this.I=!0;this.Y=this.ta=this.K=!1;this.Ha=1;this.Pa=!1;this.ma=1;b=this.s.Zc;this.Qc=1===b&&!this.za()||2===b;this.Oa=this.qa=-1;this.Td=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}ga(){return Jb(this.s,0<this.oa.length?this.oa[0]:"")}nc(){return this.P.nc()}bb(){return this.P.bb()}mc(){return this.P.mc()}za(){return this.P.za()}O(){}kc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ia(){}ha(){return this.P.ha()}Play(){}Aa(){}fb(){}Hb(){}Ka(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Td&&this.Aa(),Nb(this.s,"fade-ended",this.oa,this.Mb))}oc(){const b=this.Ha;return isFinite(b)?b:0}Gb(){return this.s.Gb()}Lb(){}sc(){}Ca(){}rc(){}tc(){}pc(){}ab(){var b=
this.Mb,a=this.oa,d=this.ha(),c=-1===this.Oa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:d,volume:c,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.za(),isLooping:this.Y,isMuted:this.Pa,resumePosition:this.pc(),pan:f,stereoPan:this.fa?
this.Wc:null}}Ac(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ca());Pb(this,b.isMuted)}};"use strict";
self.ke=class extends self.fd{constructor(b,a,d){super(b,a,d);this.P.yb.connect(this.G);this.P.onended=()=>this.Bc()}j(){this.Aa();this.P.yb.disconnect();super.j()}W(){return this.P.W()}Bc(){this.I=!0;this.qa=-1;Nb(this.s,"ended",this.oa,this.Mb)}O(){return this.W().ended}kc(){return this.I?!0:this.O()}Ia(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,d){const c=this.W();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==b&&(c.loop=b);T(this,a);c.muted&&(c.muted=!1);
if(c.currentTime!==d)try{c.currentTime=d}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.bb()}' to position '${d}': `,e)}this.s.Ba(c);this.K=this.I=!1;this.Y=b;this.ma=1}Aa(){const b=this.W();b.paused||b.pause();this.s.Ja(b);this.I=!0;this.K=!1;this.qa=-1}fb(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Hb(){!this.K||this.I||this.O()||(this.s.Ba(this.W()),this.K=!1)}Lb(){this.W().muted=this.Pa||this.Gb()}sc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Ca(){let b=this.ma;this.Qc&&(b*=this.s.fc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}rc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ia()}tc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.s.Ba(this.W()),this.ta=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.jb=null}
self.me=class extends self.fd{constructor(b,a,d){super(b,a,d);this.o=null;this.Yb=c=>this.Bc(c);this.Lc=!0;this.jb=null;this.S=this.$b=this.bc=0;this.Uc=1}j(){this.Aa();V(this);this.Yb=null;super.j()}Bc(b){this.K||this.ta||b.target!==this.jb||(this.I=this.Lc=!0,this.qa=-1,V(this),Nb(this.s,"ended",this.oa,this.Mb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Lc}kc(){return!this.o||this.I?!0:this.O()}Ia(){let b;b=this.K?this.S:this.$b+(U(this)-this.bc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,d,c){this.Uc=1;T(this,a);V(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.Yb;this.o.loop=b;this.o.start(c,d);this.K=this.I=this.Lc=!1;this.Y=b;this.ma=1;this.bc=U(this);this.$b=d}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}fb(){this.K||this.I||this.O()||(this.S=this.Ia(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.I||this.O()||(V(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,T(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.bc=U(this),this.$b=this.S,this.K=!1)}oc(){return super.oc()*this.Uc}Lb(){this.Uc=this.Pa||this.Gb()?0:1;T(this,this.Ha)}sc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ca(){let b=this.ma;this.Qc&&(b*=this.s.fc);this.o&&(this.o.playbackRate.value=b)}rc(b){this.I||this.O()||(this.K?this.S=b:(this.fb(),this.S=
b,this.Hb()))}pc(){return this.S}tc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Ia(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(V(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,T(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.bc=U(this),this.$b=this.S,this.ta=!1)}Ac(b){super.Ac(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,d,c,e){a.cancelScheduledValues(0);if(0===e)a.value=d;else switch(b=b.g.currentTime,e+=b,c){case 0:a.setValueAtTime(d,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(d,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(d,e)}}class Y{constructor(b){this.s=b;this.g=b.V();this.Hd=-1;this.T=this.Xc="";this.m=null}j(){this.g=null}N(){}U(){}ab(){return{type:this.T,tag:this.Xc,params:this.m}}}
self.ce=class extends Y{constructor(b,a,d,c,e,f,g){super(b);this.T="filter";this.m=[a,d,c,e,f,g];this.u=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=d;this.D.detune.value=c;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,d,c);X(this,this.h.gain,1-a,d,c);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,d,c);break;case 2:this.m[2]=a;X(this,this.D.detune,a,d,c);break;case 3:this.m[3]=a;X(this,this.D.Q,a,d,c);break;case 4:this.m[4]=a,X(this,this.D.gain,a,d,c)}}};
self.ae=class extends Y{constructor(b,a,d,c){super(b);this.T="delay";this.m=[a,d,c];this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.vb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.nb=W(this);this.nb.gain.value=d;this.u.connect(this.vb);this.u.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.X);this.X.connect(this.nb);this.nb.connect(this.vb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.X.disconnect();this.nb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,d,c){const e=self.$a.jd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,d,c);X(this,this.h.gain,1-a,d,c);break;case 4:this.m[1]=e(a);X(this,this.nb.gain,e(a),d,c);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,d,c)}}};
self.$d=class extends Y{constructor(b,a,d,c){super(b);this.T="convolution";this.m=[d,c];this.yd=this.xd="";this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.mb=this.g.createConvolver();this.mb.normalize=d;this.mb.buffer=a;this.u.connect(this.mb);this.u.connect(this.h);this.mb.connect(this.i)}j(){this.u.disconnect();this.mb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,
a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,d,c),X(this,this.h.gain,1-a,d,c)}}ab(){const b=super.ab();b.bufferOriginalUrl=this.xd;b.bufferUrl="";b.bufferType=this.yd;return b}};
self.de=class extends Y{constructor(b,a,d,c,e,f){super(b);this.T="flanger";this.m=[a,d,c,e,f];this.u=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.pb=W(this);this.pb.gain.value=e;this.X=this.g.createDelay(a+d);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=c;this.L=W(this);this.L.gain.value=d;this.u.connect(this.X);this.u.connect(this.h);this.X.connect(this.i);this.X.connect(this.pb);this.pb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,d,c);X(this,this.h.gain,1-a/2,d,c);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
d,c);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,d,c);break;case 8:this.m[3]=a/100,X(this,this.pb.gain,a/100,d,c)}}};
self.fe=class extends Y{constructor(b,a,d,c,e,f,g){super(b);this.T="phaser";this.m=[a,d,c,e,f,g];this.u=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=d;this.D.Q.value=c;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,d,c);X(this,this.h.gain,1-a/2,d,c);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,d,c);break;case 2:this.m[1]=a;X(this,this.D.detune,a,d,c);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,d,c);break;case 6:this.m[3]=a;X(this,this.L.gain,a,d,c);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,d,c)}}};self.ee=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,d,c){const e=self.$a.jd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),d,c)}}};
self.he=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,d,c){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,d,c)}}};
self.ie=class extends Y{constructor(b,a,d){super(b);this.T="tremolo";this.m=[a,d];this.l=W(this);this.l.gain.value=1-d/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=d/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,d,c);X(this,this.L.gain,a/2,d,c);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,d,c)}}};
self.ge=class extends Y{constructor(b,a,d){super(b);this.T="ringmod";this.m=[a,d];this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Ab=W(this);this.Ab.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Ab.gain);this.B.start(0);this.u.connect(this.Ab);this.u.connect(this.h);this.Ab.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Ab.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,d,c);X(this,this.h.gain,1-a,d,c);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,d,c)}}};
self.be=class extends Y{constructor(b,a,d,c,e,f){super(b);this.T="distortion";this.m=[a,d,c,e,f];this.u=W(this);this.dc=W(this);this.cc=W(this);b=c;.01>b&&(b=.01);this.dc.gain.value=b;this.cc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.hc=this.g.createWaveShaper();this.Fc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*d*a-a,c=0>f?-f:f,c<a?b=c:(c=1-Math.exp(-(1/b)*(c-a)),b=a+b*c),f=b*(0>f?-1:1),this.Fc[32768+e]=f,this.Fc[32768-
e-1]=-f;this.hc.curve=this.Fc;this.u.connect(this.dc);this.u.connect(this.h);this.dc.connect(this.hc);this.hc.connect(this.cc);this.cc.connect(this.i)}j(){this.u.disconnect();this.dc.disconnect();this.hc.disconnect();this.cc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,d,c){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,d,c),X(this,this.h.gain,
1-a,d,c)}}};self.Zd=class extends Y{constructor(b,a,d,c,e,f){super(b);this.T="compressor";this.m=[a,d,c,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=d;this.l.ratio.value=c;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Yd=class extends Y{constructor(b,a,d){super(b);this.T="analyser";this.m=[a,d];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=d;this.Ed=new Float32Array(this.l.frequencyBinCount);this.Sd=new Uint8Array(a);this.Qd=this.Ua=0;b=this.s;b.Ma.add(this);S(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.Ed);this.l.getByteTimeDomainData(this.Sd);const b=this.l.fftSize;let a=this.Ua=0;for(var d=0;d<b;++d){let c=(this.Sd[d]-
128)/128;0>c&&(c=-c);this.Ua<c&&(this.Ua=c);a+=c*c}d=self.$a.ue;this.Ua=d(this.Ua);this.Qd=d(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Z(b){b.stopPropagation()}
self.hb.Db(class extends self.oe{constructor(b){super(b)}hd(b,a){const d=document.createElement("input");var c=d;a.isCheckbox?(d.type="checkbox",c=document.createElement("label"),c.appendChild(d),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):d.type="button";c.style.position="absolute";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",
Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);d.addEventListener("click",()=>{var e={isChecked:d.checked};e.elementId=b;l(this,"click",e)});a.id&&(d.id=a.id);a.className&&(d.className=a.className);this.uc(c,a);return c}xc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}uc(b,a){const d="input"===b.tagName.toLowerCase()?b:b.firstChild;d.checked=a.isChecked;d.disabled=!a.isEnabled;
b.title=a.title;b===d?d.value=a.text:b.lastChild.textContent=a.text}});
